version: '3.8'
services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  server:
    build:
      context: ./server
    working_dir: /app
    volumes:
      - ./server:/app
    environment:
      - MONGO_URI=mongodb://mongo:27017/dev_db
      - PORT=5000
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    command: npm run dev

  client:
    build:
      context: ./client
      args:
        VITE_API_URL: http://server:5000/api
    ports:
      - "5173:5173"
    depends_on:
      - server

volumes:
  mongo-data:

networks:
  default:
    external:
      name: my-custom-network